---
title: "Introduction to xaringan"
subtitle: "Beautiful presentations with xaringan"
author: "Alexander Keth"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["libs/alketh.css", "libs/remark/default-fonts.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

layout:true

<div class="header"></div>
<div class="footer"><span>

---

## This is the heading

Focus on your content. Writing your presentation in a simple markdown document means you are freed from battling with the UI and layouts of individual slides and can focus entirely on writing your content. By way of example, I wrote this post in markdown and converted it to remark.js by following these 5 steps.

Focus on your content. Writing your presentation in a simple markdown document means you are freed from battling with the UI and layouts of individual slides and can focus entirely on writing your content. By way of example, I wrote this post in markdown and converted it to remark.js by following these 5 steps.

Focus on your content. Writing your presentation in a simple markdown document means you are freed from battling with the UI and layouts of individual slides and can focus entirely on writing your content. By way of example, I wrote this post in markdown and converted it to remark.js by following these 5 steps.

---

layout: false
class: split, center, middle

# Your turn!

## Do Stuff!

---

layout:true

<div class="header"></div>
<div class="footer"><span>

---

## a

s

---

## Another slide

text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text. text lots of text.

---

layout:false
class: final-slide, center, middle

# Thanks!

## You can find me at:

<a href="mailto:alexander.keth@uni-hamburg.de">alexander.keth@uni-hamburg.de

<a href="http://github.com/alketh">@alketh

